<a href="https://colab.research.google.com/github/BhusareHarshad/Data_Scientist_Interview_Practise/blob/main/Numpy_Practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Numpy Parctise')

Numpy Parctise


# NumPy Basics: Quick Reference

### 1. Python List vs. NumPy Array
NumPy arrays are the backbone of data science because they are faster and more memory-efficient than standard Python lists.


| Feature | **Python Lists** | **NumPy Arrays** |
| :--- | :--- | :--- |
| **Data Type** | Heterogeneous (mixed types) | **Homogeneous** (floats or ints or str) |
| **Memory** | High (stores object references) | **Low** (compact, contiguous blocks) |
| **Performance** | Slow (requires loops) | **Fast** (vectorized operations) |
| **Best For** | General purpose collections | Mathematical & scientific computing |

---
### **2. Cheat Sheet Syntax: Array Creation**


| Method | Purpose | Example Syntax |
| :--- | :--- | :--- |
| `np.array()` | Convert a Python list to a NumPy array | `np.array([1, 2, 3])` |
| `np.arange()` | Create a range of values (start, stop, step) | `np.arange(0, 10, 2)` |
| `np.zeros()` | Create an array filled with 0.0 (floats) | `np.zeros((3, 4))` |
| `np.ones()` | Create an array filled with 1.0 (floats) | `np.ones((3, 4))` |


---

### 3. Dimensions and Shape
Understanding the structure of your data is key to avoiding errors during matrix operations.

*   **`.ndim`**: The number of axes (dimensions). 1D = Vector, 2D = Matrix, 3D = Tensor.
*   **`.shape`**: A tuple representing the size of the array along each axis (e.g., `(rows, columns)`).

```python
# Data type change
k.astype('float')

np.array([1,2,3], dtype='f')


In [3]:
import numpy as np

k = np.array([1,2,3])

In [9]:
print(type(k),'|', k.ndim,'|', k.shape)

<class 'numpy.ndarray'> | 1 | (3,)


In [11]:
m = np.arange(0,10,2)
print(m)

[0 2 4 6 8]


In [150]:
np.ones((2,1), dtype='int')

array([[1],
       [1]])

In [30]:
np.array([1,2,3], dtype='f')

array([1., 2., 3.], dtype=float32)

In [16]:
z = np.zeros((4,2))
print(z)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [26]:
test_ = [2, 'a']

In [27]:
np.array(test_)

array(['2', 'a'], dtype='<U21')

In [29]:
k.astype('float')

array([1., 2., 3.])

# **Advanced NumPy Operations**

### **1. Accessing & Reshaping Data**


| **Operation** | **Method** | **Example Syntax** | **Description** |
| :--- | :--- | :--- | :--- |
| **Indexing** | `arr[i]` | `arr[2]` | Access a single element at index `i`. |
| **Slicing** | `arr[start:stop:step]` | `arr[1:5:2]` | Extract a sub-section of the array. |
| **Reshape** | `arr.reshape(r, c)` | `arr.reshape(2, 5)` | Changes shape without changing data. |
| **Transpose** | `arr.T` or `arr.transpose()`| `arr.T` | Flips rows and columns. |

---

### **2. Advanced Selection & Stacking**


| **Method** | **Purpose** | **Example Syntax** |
| :--- | :--- | :--- |
| **Fancy Indexing** | Access multiple specific elements using a list of indices. | `arr[[0, 2, 4]]` |
| **VStack** | Stack arrays **vertically** (row-wise). | `np.vstack((a, b))` |
| **HStack** | Stack arrays **horizontally** (column-wise). | `np.hstack((a, b))` |

---

### **Quick Start Code**

```python
import numpy as np

# 1. Reshape & Transpose
a = np.arange(6)             # [0, 1, 2, 3, 4, 5]
b = a.reshape(2, 3)          # [[0, 1, 2], [3, 4, 5]]
print(b.T)                   # [[0, 3], [1, 4], [2, 5]]

# 2. Slicing (Rows, Columns)
# Get all rows, but only the first two columns
print(b[:, 0:2])             

# 3. Stacking
x = np.array([1, 2])
y = np.array([3, 4])
print(np.vstack((x, y)))     # [[1, 2], [3, 4]]
print(np.hstack((x, y)))     # [1, 2, 3, 4]

# 4. Fancy Indexing
data = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(data[indices])         # [10, 30, 50]


In [33]:
k

array([1, 2, 3])

In [32]:
k[2]

np.int64(3)

In [40]:
m = np.arange(1,11,1)

In [41]:
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
m[0:6:2]

array([1, 3, 5])

In [48]:
m = m.reshape(2,5)

In [49]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
m.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [57]:
## Fancy indexing

m[[1,]]

array([[ 6,  7,  8,  9, 10]])

In [58]:
m[m % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [63]:
a = [1,2,3]
b = [4,5,6]

h = np.hstack((a,b))
print(k)

[1 2 3 4 5 6]


In [64]:
v = np.vstack((a, b))

print(v)

[[1 2 3]
 [4 5 6]]


# **NumPy: Math, Sorting & Aggregation**

### **1. Mathematical Operations**
NumPy performs **element-wise** operations by default, which is much faster than Python loops.


| Operation | Method | Example Syntax |
| :--- | :--- | :--- |
| **Basic Math** | `+`, `-`, `*`, `/` | `a + b` (Element-wise) |
| **Dot Product** | `np.dot()` or `@` | `a @ b` (Matrix Multiplication) |
| **Square Root** | `np.sqrt()` | `np.sqrt(a)` |
| **Exponent** | `np.exp()` | `np.exp(a)` |

---

### **2. Sorting & Searching**
Efficiently organizing data or finding specific values.


| Operation | Method | Description |
| :--- | :--- | :--- |
| **Sort** | `np.sort(arr)` | Returns a sorted copy of the array. |
| **Argsort** | `np.argsort(arr)` | Returns the **indices** that would sort the array. |
| **Where** | `np.where(cond)` | Returns indices where a condition is True. |

---

### **3. Aggregation (Statistics)**
Functions used to summarize data across the entire array or specific axes.


| Operation | Method | Example Syntax |
| :--- | :--- | :--- |
| **Sum** | `np.sum()` | `np.sum(arr, axis=0)` (Sum of columns) |
| **Mean** | `np.mean()` | `np.mean(arr)` (Average) |
| **Max / Min** | `np.max()`, `np.min()`| `np.max(arr)` (Highest value) |
| **Standard Dev**| `np.std()` | `np.std(arr)` (Spread of data) |

---

### **Quick Start Code**

```python
import numpy as np

# 1. Multiplication vs. Dot Product
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a * b)    # Element-wise: [[5, 12], [21, 32]]
print(a @ b)    # Matrix Product: [[19, 22], [43, 50]]

# 2. Aggregation by Axis
data = np.array([[1, 2], [3, 4]])
print(np.sum(data, axis=0)) # Columns: [4, 6]
print(np.sum(data, axis=1)) # Rows: [3, 7]

# 3. Sorting
unsorted = np.array([3, 1, 4, 2])
print(np.sort(unsorted))    # [1, 2, 3, 4]

In [66]:
a = np.array([1,2])
b = np.array([2,2])

a+b

array([3, 4])

In [67]:
a * b

array([2, 4])

In [69]:
t = a @ b ## broadcasting and then multiplication (dot product)

print(t)

6


In [70]:
np.sqrt(t)

np.float64(2.449489742783178)

In [73]:
np.exp(t) ## 2.71^6

np.float64(403.4287934927351)

In [91]:
st = np.array([3,6,8,10,2])

In [92]:
np.sort(st)

array([ 2,  3,  6,  8, 10])

In [93]:
np.argsort(st) ## indices that would sort (4th at 0th)

array([4, 0, 1, 2, 3])

In [97]:
## np.where(cond, x, y) OR np.where(cond, )

np.where(st > 3, st, 100)

array([100,   6,   8,  10, 100])

In [98]:
st.min()

np.int64(2)

In [99]:
st.max()

np.int64(10)

In [100]:
st.mean()

np.float64(5.8)

In [101]:
st.std()

np.float64(2.993325909419153)

In [102]:
st.sum()

np.int64(29)

In [105]:
np.sum(v, axis=0)

array([5, 7, 9])

In [104]:
v

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.random.rand(2,3) ## Uniform Distribution [0,1]

array([[0.05788494, 0.38786323, 0.5961512 ],
       [0.99456125, 0.65440633, 0.62357155]])

In [112]:
np.random.randn(2,3) ## Normal Distribution [-1, 1]

array([[ 1.28565151,  1.14776905,  0.05351082],
       [-1.22188261, -2.07001437,  0.14590217]])

In [113]:
## --

# **NumPy Broadcasting**

Broadcasting allows NumPy to perform arithmetic operations on arrays of **different shapes**, as long as they are compatible.

---

### **1. Rules of Broadcasting**
For two arrays to be compatible for broadcasting, NumPy compares their dimensions from **right to left**:
1.  The dimensions must be **equal**, OR
2.  One of the dimensions must be **1**.


| Scenario | Array A Shape | Array B Shape | Resulting Shape |
| :--- | :--- | :--- | :--- |
| **Scalar + 1D** | `(3,)` | `(1,)` or Scalar | `(3,)` |
| **2D + 1D** | `(3, 3)` | `(3,)` | `(3, 3)` |
| **Compatible** | `(4, 3)` | `(1, 3)` | `(4, 3)` |
| **Incompatible**| `(4, 3)` | `(4, 2)` | **Error!** |

---

### **2. Cheat Sheet Syntax**


| **Operation** | **Purpose** | **Example Syntax** |
| :--- | :--- | :--- |
| **Scalar Broadcast** | Add/Mult a single number to every element | `arr + 5` |
| **Row-wise** | Apply a 1D vector to every row of a 2D matrix | `matrix + row_vec` |
| **Column-wise** | Apply a 1D vector to every column (needs reshape) | `matrix + col_vec.reshape(-1, 1)` |

---

### **Quick Start Code**

```python
import numpy as np

# 1. Scalar Broadcasting
a = np.array([10, 20, 30])
print(a + 5)             # Output: [15, 25, 35]

# 2. 2D + 1D Broadcasting
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]]) # Shape (2, 3)
row_vec = np.array([1, 0, 1])  # Shape (3,)

# The row_vec is "stretched" to match the 2 rows of the matrix
print(matrix + row_vec)  
# Result: [[2, 2, 4], [5, 5, 7]]

# 3. Handling Incompatible Shapes
# To broadcast column-wise, the vector must have a shape of (2, 1)
col_vec = np.array([10, 20])   # Shape (2,) -> Needs reshape
print(matrix + col_vec.reshape(2, 1))


In [114]:
a = np.array([10,20,30])

In [115]:
print(a + 6)  ## 1D Broadcasting

[16 26 36]


In [116]:
matrix = np.array([[1,2,3],
                   [4,5,6]])
row_vec = np.array([1,0,1])

In [117]:
matrix.shape, matrix.ndim

((2, 3), 2)

In [119]:
row_vec.shape, row_vec.ndim

((3,), 1)

In [ ]:
## (2,3) & (3,1)

In [120]:
matrix @ row_vec

array([ 4, 10])

# **NumPy Array Splitting**

Splitting is the opposite of stacking; it breaks one array into multiple smaller sub-arrays.

---

### **1. Split Operations**


| **Operation** | **Method** | **Description** | **Requirement** |
| :--- | :--- | :--- | :--- |
| **Horizontal Split** | `np.hsplit(arr, n)` | Splits array **column-wise** (horizontally). | `n` must divide columns evenly. |
| **Vertical Split** | `np.vsplit(arr, n)` | Splits array **row-wise** (vertically). | `n` must divide rows evenly. |
| **Generic Split** | `np.split(arr, n, axis)` | Splits along a specified axis (0 for rows, 1 for cols). | Flexible for N-dimensions. |

---

### **2. Cheat Sheet Syntax**


| **Function** | **Purpose** | **Example Syntax** |
| :--- | :--- | :--- |
| `np.hsplit()` | Break a matrix into multiple vertical sections | `np.hsplit(matrix, 2)` |
| `np.vsplit()` | Break a matrix into multiple horizontal sections | `np.vsplit(matrix, 3)` |
| `np.array_split()` | Split into **unequal** parts (doesn't raise error) | `np.array_split(arr, 3)` |

---

### **Quick Start Code**

```python
import numpy as np

# Create a 4x4 matrix
data = np.arange(16).reshape(4, 4)

# 1. Vertical Split (Split into 2 arrays of 2 rows each)
upper, lower = np.vsplit(data, 2)
# upper shape: (2, 4), lower shape: (2, 4)

# 2. Horizontal Split (Split into 2 arrays of 2 columns each)
left, right = np.hsplit(data, 2)
# left shape: (4, 2), right shape: (4, 2)

# 3. Using np.split (Specific axis)
# Same as vsplit
parts = np.split(data, 2, axis=0)

# 4. Unequal Splitting
# If you try to split 4 columns into 3 using hsplit, it crashes.
# np.array_split handles it by making sections as equal as possible.
unequal_parts = np.array_split(data, 3, axis=1)


In [125]:
a = np.array([1,2,3,4,5,6])

In [129]:
np.split(a,3, axis=0)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [130]:
b = np.array([[1,2,3,4,5,6],
             [7,8,9,10,11,12]])

In [133]:
np.split(b, 3, axis=1)

[array([[1, 2],
        [7, 8]]),
 array([[ 3,  4],
        [ 9, 10]]),
 array([[ 5,  6],
        [11, 12]])]

In [142]:
vh = np.array([[1,2,3],[4,5,6]])

In [144]:
np.hsplit(vh, 3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [146]:
np.vsplit(vh, 2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

# **NumPy: Linear Algebra (linalg)**

The `numpy.linalg` module provides a comprehensive suite of functions for matrix operations, solving linear systems, and finding decompositions.

---

### **1. Matrix & Vector Products**
These operations go beyond element-wise multiplication to perform standard algebraic products.


| **Operation** | **Method** | **Example Syntax** | **Description** |
| :--- | :--- | :--- | :--- |
| **Dot Product** | `np.dot(a, b)` | `a.dot(b)` | 1D: Inner product; 2D: Matrix multiplication. |
| **Matrix Multiply** | `np.matmul(a, b)` | `a @ b` | Preferred for matrix multiplication; handles 3D stacks. |
| **Inner Product** | `np.inner(a, b)` | `np.inner(a, b)` | Sum of products of corresponding elements. |
| **Outer Product** | `np.outer(a, b)` | `np.outer(a, b)` | Computes the outer product of two vectors. |

---

### **2. Solving & Inverting**
Tools for finding solutions to linear equations ($Ax = b$) and calculating matrix properties.


| **Operation** | **Method** | **Example Syntax** | **Description** |
| :--- | :--- | :--- | :--- |
| **Solve System** | `la.solve(A, b)` | `np.linalg.solve(A, b)` | Finds $x$ such that $Ax = b$. |
| **Inverse** | `la.inv(A)` | `np.linalg.inv(A)` | Computes the multiplicative inverse of a square matrix. |
| **Determinant** | `la.det(A)` | `np.linalg.det(A)` | Returns the determinant of a matrix. |
| **Matrix Rank** | `la.matrix_rank()` | `np.linalg.matrix_rank(A)`| Returns the number of linearly independent rows/cols. |
| **Trace** | `np.trace(A)` | `np.trace(A)` | Returns the sum of the diagonal elements. |

---

### **3. Decompositions & Norms**
Advanced functions often used in Machine Learning and data transformation.


| **Operation** | **Method** | **Example Syntax** | **Description** |
| :--- | :--- | :--- | :--- |
| **Eigenvalues** | `la.eig(A)` | `vals, vecs = np.linalg.eig(A)` | Returns eigenvalues and eigenvectors. |
| **SVD** | `la.svd(A)` | `u, s, vh = np.linalg.svd(A)` | Singular Value Decomposition. |
| **Norm** | `la.norm(x)` | `np.linalg.norm(x)` | Matrix or vector norm (e.g., L2 norm). |

---

### **Quick Start Code**

```python
import numpy as np

# Define a 2x2 matrix and a vector
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

# 1. Solving a system of linear equations (3x + y = 9; x + 2y = 8)
x = np.linalg.solve(A, b)
print(f"Solution x: {x}") # Output: [2. 3.]

# 2. Matrix multiplication (@ is shorthand for matmul)
B = np.array([[1, 0], [0, 1]]) # Identity matrix
product = A @ B

# 3. Eigenvalues and Eigenvectors
values, vectors = np.linalg.eig(A)

# 4. Transpose (Flip rows and columns)
print(A.T)
